import test from 'ava'
import path from 'path'

const IntTypes = require(path.resolve(__dirname, '..', 'dist', 'itkIntTypes.js'))
const FloatTypes = require(path.resolve(__dirname, '..', 'dist', 'itkFloatTypes.js'))
const PixelTypes = require(path.resolve(__dirname, '..', 'dist', 'itkPixelTypes.js'))
const readImageLocalFile = require(path.resolve(__dirname, '..', 'dist', 'itkreadImageLocalFile.js'))
const itkConfig = require(path.resolve(__dirname, '..', 'dist', 'itkConfig.js'))
itkConfig.imageIOsPath = path.resolve(__dirname, '..', 'dist', 'itkImageIOs')

test('Test reading a PNG file', t => {
  const testFilePath = path.resolve(__dirname, '..', 'build', 'ExternalData', 'test', 'Input', 'cthead1.png')
  return readImageLocalFile(testFilePath).then(function (image) {
    t.is(image.imageType.dimension, 2)
    t.is(image.imageType.componentType, IntTypes.UInt8)
    t.is(image.imageType.pixelType, PixelTypes.RGB)
    t.is(image.imageType.components, 3)
    t.is(image.origin[0], 0.0)
    t.is(image.origin[1], 0.0)
    t.is(image.spacing[0], 1.0)
    t.is(image.spacing[1], 1.0)
    t.is(image.direction.getElement(0, 0), 1.0)
    t.is(image.direction.getElement(0, 1), 0.0)
    t.is(image.direction.getElement(1, 0), 0.0)
    t.is(image.direction.getElement(1, 1), 1.0)
    t.is(image.size[0], 256)
    t.is(image.size[1], 256)
    t.is(image.buffer.length, 196608)
  })
})

test('Test reading a NRRD file', t => {
  const testFilePath = path.resolve(__dirname, '..', 'build', 'ExternalData', 'test', 'Input', 'vol-raw-little.nrrd')
  return readImageLocalFile(testFilePath).then(function (image) {
    t.is(image.imageType.dimension, 3)
    t.is(image.imageType.componentType, FloatTypes.Float64)
    t.is(image.imageType.pixelType, PixelTypes.Scalar)
    t.is(image.imageType.components, 1)
    t.is(image.origin[0], 0.0)
    t.is(image.origin[1], 0.0)
    t.is(image.origin[2], 0.0)
    t.is(image.spacing[0], 1.0)
    t.is(image.spacing[1], 1.0)
    t.is(image.spacing[2], 1.0)
    t.is(image.direction.getElement(0, 0), 1.0)
    t.is(image.direction.getElement(0, 1), 0.0)
    t.is(image.direction.getElement(1, 0), 0.0)
    t.is(image.direction.getElement(1, 1), 1.0)
    t.is(image.size[0], 5)
    t.is(image.size[1], 6)
    t.is(image.size[2], 7)
    t.is(image.buffer.length, 210)
    t.is(image.buffer[2], 5.0)
  })
})
