packages:
  - 'packages/**'
  - 'examples/debugging'
  - 'examples/node-js'
  - 'examples/inputs-outputs'
  - 'examples/inputs-outputs/typescript'
  - 'examples/different-input-types'
  - 'examples/hello-world'
  - 'examples/mean-squares-versor-registration'
  - 'examples/mean-squares-versor-registration/typescript'
  - '!packages/core/typescript/create-itk-wasm/test/**'
  - '!**/src'
  - '!**/dist'
  - '!**/pyodide'
overrides:
  '@shoelace-style/shoelace': ^2.12.0
  '@types/node': ^24.0.3
  esbuild: ^0.25.1
  start-server-and-test: ^2.0.12
  ava: ^6.1.3
  '@playwright/test': ^1.57.0
  shx: ^0.4.0
  typescript: ^5.8.3
  vite: ^6.2.3
allowBuilds:
  esbuild: true
  protobufjs: true
