#!/usr/bin/env bash

# Generate itk_wasm_env_vars.sh for use in Docker builds
# This script sources the root itk_wasm_env.bash and extracts only
# the variables needed by the Dockerfile

set -eo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
root_dir="$(cd "$script_dir/../../.." && pwd)"

# Source the main environment file
# Note: We need to handle the fact that itk_wasm_env.bash tries to parse
# package.json files which may not work in all contexts
export ITK_WASM_DEV_DOCKER_TAG="${ITK_WASM_DEV_DOCKER_TAG:-latest}"

# Extract the core variables we need
source "$root_dir/itk_wasm_env.bash" 2>/dev/null || {
  # If sourcing fails (e.g., due to jq commands), extract manually
  ITK_WASM_DCMTK_REPOSITORY="${ITK_WASM_DCMTK_REPOSITORY:-https://github.com/InsightSoftwareConsortium/DCMTK}"
  ITK_WASM_DCMTK_GIT_TAG="${ITK_WASM_DCMTK_GIT_TAG:-2fe4dacbe9c343dba350fcff6eab365241636623}"
  ITK_WASM_ITK_REPOSITORY="${ITK_WASM_ITK_REPOSITORY:-https://github.com/thewtex/ITK}"
  ITK_WASM_ITK_BRANCH="${ITK_WASM_ITK_BRANCH:-itkwasm-2025-03-19-25d3162371}"
}

# Generate the env vars file for Docker
cat > "$script_dir/itk_wasm_env_vars.sh" << EOF
#!/usr/bin/env sh
# Auto-generated by generate-env-vars.sh - DO NOT EDIT
# Generated from: $root_dir/itk_wasm_env.bash

export ITK_WASM_DCMTK_REPOSITORY="${ITK_WASM_DCMTK_REPOSITORY}"
export ITK_WASM_DCMTK_GIT_TAG="${ITK_WASM_DCMTK_GIT_TAG}"
export ITK_WASM_ITK_REPOSITORY="${ITK_WASM_ITK_REPOSITORY}"
export ITK_WASM_ITK_BRANCH="${ITK_WASM_ITK_BRANCH}"
EOF

chmod +x "$script_dir/itk_wasm_env_vars.sh"

echo "Generated $script_dir/itk_wasm_env_vars.sh with:"
echo "  ITK_WASM_ITK_REPOSITORY=${ITK_WASM_ITK_REPOSITORY}"
echo "  ITK_WASM_ITK_BRANCH=${ITK_WASM_ITK_BRANCH}"
echo "  ITK_WASM_DCMTK_REPOSITORY=${ITK_WASM_DCMTK_REPOSITORY}"
echo "  ITK_WASM_DCMTK_GIT_TAG=${ITK_WASM_DCMTK_GIT_TAG}"
