#!/usr/bin/env bash

#
# Configure and build the CMake project with source code in the current
# directory in "./web-build".
#
# Any extra arguments passed to the script and passed to the cmake
# configuration step.
#

mkdir -p ./web-build

cmake \
   --no-warn-unused-cli \
   -Bweb-build \
   -H. \
   -DCMAKE_BUILD_TYPE:STRING=Release \
   -DITK_DIR:PATH=/ITK-build \
   -DVTK_DIR:PATH=/VTK-build \
   -DSlicerExecutionModel_DIR:PATH=/SlicerExecutionModel-build \
   -GNinja \
     "$@" && \
ninja -Cweb-build
