[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "@bindgenPackageName@"
readme = "README.md"
license-expression = "Apache-2.0"
dynamic = ["version"]
description = "@bindgenPackageDescription@"
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Programming Language :: C++",
  "Environment :: WebAssembly",
  "Environment :: WebAssembly :: Emscripten",
  "Environment :: WebAssembly :: WASI",
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
keywords = [
  "itkwasm",
  "webassembly",@bindgenKeywords@
]

requires-python = ">=3.8"
dependencies = [
    "itkwasm >= 1.0.b184",@bindgenDependencies@
]

[tool.hatch.version]
path = "@bindgenPyPackage@/_version.py"

[tool.hatch.envs.default]
dependencies = [
  "pytest",@bindgenHatchEnvDependencies@
]

[project.urls]
Home = "@bindgenProjectRepository@"
Source = "@bindgenProjectRepository@"
@bindgenHatchEnvScripts@

[tool.hatch.build]
exclude = [
  "/examples",
]
